@echo off
echo Reiniciando backend...
cd backend
echo Sincronizando banco de dados...
node -e "require('dotenv').config(); const db = require('./config/database'); db.sync({force: false}).then(() => {console.log('✅ DB sincronizado'); process.exit(0);}).catch(e => {console.error('❌ Erro:', e.message); process.exit(1);})"
echo Iniciando servidor...
node server.js